### ISSUE TITLE
Reduce repo file size?

### ISSUE THREAD

**Issue by giswqs** [JackMcKew/pandas_alive#15]
The current file size of the repo is **1.64 GB**,  which is gigantic and takes a while to download. I found this huge file within the `.git` directory. 

```
1.6G    ./.git/objects/pack/pack-6447cf1a836f2030aae5c189d6b0051224081a89.pack
```

**Comment by JackMcKew** [comment]
Hi @giswqs 

Thank you for raising this, this must be something in the git history

I'll run BFG cleaner over the repo 👍

**Comment by JackMcKew** [comment]
The repo is now ~180MB after removing all those large unnecessary files.

Thank you for your contribution 😄

**Comment by giswqs** [comment]
Awesome! The repo file size is much more manageable now.
