### ISSUE TITLE
Relative Links in README

### ISSUE THREAD

**Issue by JackMcKew** [JackMcKew/pandas_alive#18]
The relative links in the README are causing the documentation page on PyPI to have broken links all through it (especially with the visualisations 😲)

The fix for this would be to append the GitHub url to each of the relative links ☺️ (eg, GitHub.com/pandas_alive/)

**Comment by SoundSpinning** [comment]
Hi mate. I had a look around at this. I read your blog post (good work there) about Sphinx, and tried. I started off your `develop` branch, but I think some contents in docs folder are outdated? So, then I tried off `Main` branch, but I got a bit lost 😕; e.g. in there `README.rst` seems outdated? I think I just don't understand/know enough the workflow required to use `Sphinx` properly, and I feel I'll break something and waste your time.

In my head, it seems that I should be able to place the files with relative paths that are not currently working somewhere in the `gh-pages` branch, like you do with `_images` so they are all found in the docs, but I cannot work out how to do this automatically from Sphinx. I'm assuming that we are just not manually editing each relative path for each deployment.

**Comment by JackMcKew** [comment]
No worries mate, I'm happy to sort it out when I get the chance

If it helps any, everything README stems from the README.ipynb jupyter notebook, it gets converted to markdown, and the markdown gets converted to restructured text by GitHub Actions whenever a new version is released on main. So I was thinking all's needed would be to make all the images/urls in the README.ipynb direct to GitHub and that'd be all's needed

**Comment by JackMcKew** [comment]
Originally documented how it was all set up here

https://jackmckew.dev/make-a-readme-documentation-with-jupyter-notebooks.html

**Comment by SoundSpinning** [comment]
I originally thought the same as you suggest. But then, when you're developing and testing new vids in readme, the relative paths are required? Or else, the github ones will only look to what's there already.
My original thought was to add a variable at the start of the Jupyter readme for devs with say `root = "./"`, and then before commit, comment that line out, and switch to another one with: `root = "https://github.com/JackMcKew/pandas_alive/"`. Both appended to the start of hyperlinks where required. 
Is that what you meant so it works in dev and deployment modes? Then, I can do that one. Let me know.

**Comment by SoundSpinning** [comment]
> 
> 
> Originally documented how it was all set up here
> 
> https://jackmckew.dev/make-a-readme-documentation-with-jupyter-notebooks.html

This is great, I really like what you're doing with the blog. That in my book, makes you already a top engineer! ✈

**Comment by JackMcKew** [comment]
I didn't even think about when working locally, but I think it's pretty straightforward where the animation will be coming from eventually so I'm inclined to put them all as the direct URL and if you're developing locally can easily find and replace. I feel like the root url showing in the README would be fluff we don't need.

Thank you very much! I really enjoy writing it 😌

**Comment by SoundSpinning** [comment]
Understood, I also thought it was an 'ugly' approach. I'll do the edits in the readme later on, and post a PR with that.

**Comment by JackMcKew** [comment]
You're an absolute legend! Thank you so much, I really do appreciate the help 😊

**Comment by SoundSpinning** [comment]
It always goes both ways when collaborating, so likewise!

**Comment by JackMcKew** [comment]
Thank you so much for raising & fixing this, you're fantastic! 😄
