### ISSUE TITLE
Maybe someting wrong with font in my picture

### ISSUE THREAD

**Issue by lsj8924** [JackMcKew/pandas_alive#22]
the font in my picture is blurred，just like this.  It's from the example.
![example-electricity-generated-australia](https://user-images.githubusercontent.com/8875594/103735670-83337180-5029-11eb-8b60-cc3981a6699e.gif)

**Comment by JackMcKew** [comment]
Which video writer were you using in this example? In memory PIL?

**Comment by lsj8924** [comment]
My workspace is Jupyter. video writer is PIL. But actually   I have installed both PIL and ffmpeg. I make my effort to grapple the problem. As you say something wrong with PIL, so I uninstall the PIL. but it does not work again—“Python3.x No module named 'PIL”. So I have to reinstall  the Pillow.

**Comment by JackMcKew** [comment]
Could you please provide:

- Any system specifications for the machine you are using (OS, Python version, etc)
- The code used to produce your example

**Comment by lsj8924** [comment]
I solved the problem. The pciture  made out from Jupyter  is blurred.  The command line is OK. 
What's mroe, the size of Gif format is way larger than MP4. It's better use the MP4 format.  Sometimes Gif have to employed, It's better covert MP4 format to gif, but grnerate directly with pandas_alive.  with a transform, the size almost  compress to 1/7.

**Comment by JackMcKew** [comment]
Fantastic to hear that you solved the problem

`pandas_alive` supports multiple writers for this very reason, the default of using PIL for in memory GIF writing is a matter of convenience.
