### ISSUE TITLE
Can't install. Error in Pillows

### ISSUE THREAD

**Issue by shinyidol** [JackMcKew/pandas_alive#32]
**Describe the bug**
Run pip script and errors from issue with pillows

**To Reproduce**
1. run install pip script
2. errors

**Expected behavior**
install

**Tested On**
Win/python 3.9.5/pip 21.1.2
macOS/python 3.9.5/pip 21.1.2

**Additional context**

`Installing collected packages: pillow, attrs, pandas-alive
  Attempting uninstall: pillow
    Found existing installation: Pillow 8.2.0
    Uninstalling Pillow-8.2.0:
      Successfully uninstalled Pillow-8.2.0
    Running setup.py install for pillow ... error
    ERROR: Command errored out with exit status 1:`

**Comment by JackMcKew** [comment]
Have you tried installing it within a virtual environment? That error message seems to imply an existing installation causing issues

**Comment by shinyidol** [comment]
Got it working. Thanks.
