### ISSUE TITLE
error message although writer library is installed

### ISSUE THREAD

**Issue by manfred2020** [JackMcKew/pandas_alive#5]
hello, i wanted to try your interesting library, but i always get an error (animated figure does not show up on screen and i also cannot save figure as gif).

errors (when trying to save figure):

with version 0.1.13 i get "RuntimeError: Ensure that a matplotlib writer library is installed, see https://github.com/JackMcKew/pandas_alive/blob/master/README.md#requirements for more details".

with version 0.1.12 i got "'MovieWriterRegistry' object is not an iterator".

im running pandas-alive on windows 10, python 3.7.7, matplotlib 3.2.1, pandas 1.0.3, Pillow 7.1.2.

**Comment by JackMcKew** [comment]
Hi!

Thank you for raising this.

Currently Pandas-Alive only supports writing to a GIF via [imagemagick](https://imagemagick.org/).

It's in the to-do list to investigate if Pillow will work for GIFs as well.

**Comment by JackMcKew** [comment]
I cannot get Pillow to generate GIFs.

It just returns `Index Error: list index out of range` whenever I try to invoke `anim.save(filename,writer=Pillow)` or `anim.save(filename,writer=PillowWriter())` 

PRs are most definitely welcome if you can make this work, otherwise I have altered Pandas_Alive to state that Pillow is not supported.

In preparation for the next release, you will be able to define your own custom writer.

**Comment by manfred2020** [comment]
thanks for the fast reply!

so right now out of these

"Ensure to have one of the supported tooling software installed prior to use!

    ffmpeg
    ImageMagick
    Pillow"

only imagmagick works? or can i save the animated figure with another file format (not gif) when using pillow?

**Comment by JackMcKew** [comment]
Great question!

I'd been planning a new release to make sure that Pillow was explicitly unsupported after my experience yesterday, but I did only try producing GIFs. I'll see if any other file type works first.

**Comment by JackMcKew** [comment]
Pillow doesn't seem to play nice whatever the file type is.

For future readers the error that is being raised each time the `Pillow` library is specified is:
``` bash
Exception has occurred: IndexError
list index out of range
  File "C:\Users\jackm\Documents\GitHub\pandas-alive\pandas_alive\_base_chart.py", line 555, in save
    anim.save(filename, fps=self.fps, dpi=self.dpi,writer=self.writer)
  File "C:\Users\jackm\Documents\GitHub\pandas-alive\pandas_alive\plotting.py", line 339, in plot
    line_race.save(verify_filename(filename))
  File "C:\Users\jackm\Documents\GitHub\pandas-alive\playground.py", line 12, in <module>
    covid_df.sum(axis=1).fillna(0).plot_animated(filename='test.mp4',kind='line',period_label={'x':0.1,'y':0.9},enable_progress_bar=True,writer="pillow")
```
