### ISSUE TITLE
backend_agg.py:214: RuntimeWarning: Glyph 150 missing from current font. gif doesn't show

### ISSUE THREAD

**Issue by qinghongao** [JackMcKew/pandas_alive#8]
Hi Jack. 
Got bunch of warning and I can't see gif file in notebook as well

**Comment by JackMcKew** [comment]
Hi @qinghongao 

I think this only happens on certain cells within the notebook, and it's just a warning, it doesn't crash the program. The output still comes out as expected, thus I ignored this warning initially.

If you determine the source of the warning and potentially find a fix for it, please make a pull request, they are most definitely welcome! https://github.com/JackMcKew/pandas_alive/pulls

Ensure to check the file (*.gif) still comes out in the folder where the notebook is located,

Note that pandas_alive doesn't show the gif inline within the notebook, only if you show it as an image in a markdown cell (eg ![GIF](file.gif)
